### ISSUE TITLE
Feature idea: button to randomly generate username

### ISSUE THREAD

**Issue by elimisteve** [cryptag/leapchat#13]

**Comment by jimmcgaw** [comment]
Maybe this? https://github.com/cryptag/leapchat/compare/random_username?expand=1

**Comment by elimisteve** [comment]
Hey that looks great, thanks!  Let's add a "Random Username" button to the
username modal or something like that, and maybe also display one's own
username on outgoing messages so users who choose a random username don't
forget who they are (which could be bad when other users mention them and
they don't know they're being talked to... or we could copy the Backchannel
design and display the user's username in the upper left along a side
panel, perhaps one that slides out when an upper-left button is pressed,
just like with Slack's mobile app), then merge this in.

A relatively pressing issue is an odd Bootstrap-related CSS thing that
happens once the window width is <= 991px.  The upshot is that, on mobile,
the last couple messages of the chat get cut off.  It's as if

.message-list {
  margin-bottom: 100px;
}

doesn't get applied.  Looks like changing Bootstrap's default
responsiveness behavior could be the answer?  I'm not sure; I'm still
mostly CSS illiterate.  Thanks.

--Steve
