### ISSUE TITLE
Reduxifying alert messages

### ISSUE THREAD

**Issue by Spetastian** [cryptag/leapchat#134]
Move the alert message state management from `App.js` into Redux as actions to be dispatched. Then instead of using `setState` in the `displayAlert` method we update the application state with Redux in a reducer when a specific alert action is dispatched. The app component should connect to that part of the application state in `connectStateToProps` in order to be able to access it through `this.props`. Also don't forget to add the dispatching of the actions to `mapDispatchToProps` when connecting the component to Redux.

Right now the displaying of an alert message looks like this in `App.js`:

```javascript
  displayAlert(message, alertStyle = 'success') {

    this.setState({
      alertMessage: message,
      alertStyle: alertStyle
    })

  }
```

It takes a message and a string stating what type of alert (alertStyle) that should be displayed. When migrating this behavior to Redux actions, I suggest that we have a single action called something like `ALERT_SHOW` but we have one action creator for every type so that the component dispatching the actions would not need to care about the alertStyle string value.

This means that instead of doing this (which is how it looks today without using Redux):
`this.displayAlert(errStr, 'warning');`

We will be able to instead do something this:
`this.props.warningAlert(errStr)`

I would suggest creating new files for alert actions ( `/src/actions/alertActions` ) and a completely new reducer ( `/src/reducers/alertReducer` ).

**Comment by elimisteve** [comment]
:+1: great @Spetstian, thank you; I'll work on this

**Comment by Spetastian** [comment]
Tis done!
