### ISSUE TITLE
Add rel "nofollow noreferrer noopener" attribute to Links.

### ISSUE THREAD

**Issue by Moe-Shoman** [cryptag/leapchat#170]
Prevents tab napping and information leakage.
https://medium.com/@jitbit/target-blank-the-most-underestimated-vulnerability-ever-96e328301f4c
https://mathiasbynens.github.io/rel-noopener/

**Comment by elimisteve** [comment]
Closed by #171

**Comment by elimisteve** [comment]
@Moe-Shoman I just made this repo's default branch `develop` so that accepted PRs (like this one) will automatically close issues with their commit messages.
