### ISSUE TITLE
Does or will leapchat team work with LEAP.se?

### ISSUE THREAD

**Issue by NIXOYE** [cryptag/leapchat#177]
https://leap.se/ is a nonprofit based around giving users access to encryption software and they are doing great work with their development of Bitmask a way for people to easily create and use their own vpns. https://0xacab.org/leap/bitmask-dev is the current repo for their project.

**Comment by elimisteve** [comment]
Hi @NIXOYE, good question!  I agree that the LEAP project does great work.  I spoke with 1 of their engineers about a year ago to discuss some ideas, but our groups have not joined forces.

Bitmask is totally easy to use and I support what they're doing there for sure.

If there is significant overlap between what our respective groups are trying to accomplish, working together would be great.

Thanks for the question!

**Comment by NIXOYE** [comment]
AWESOme, I hope you reach out again to see if there are things you could all collaborate on now that both projects have been developed significantly
