### ISSUE TITLE
develop: After initial messages load, doesn't scroll down to bottom

### ISSUE THREAD

**Issue by elimisteve** [cryptag/leapchat#180]
@Spetastian How about we scroll to the bottom whenever messages come in at all, not just after app init?

**Comment by Spetastian** [comment]
@elimisteve This should do it: https://github.com/cryptag/leapchat/pull/184

It worked when i tested locally. It scrolls down every time a new message arrives. Though based on you opinion about how and when it should scroll down and when the sound should be played, i could do some tweaking. What do you think?
