### ISSUE TITLE
No way to delete messages

### ISSUE THREAD

**Issue by meridia15** [cryptag/leapchat#203]
Written messages cannot be deleted. A stranger who enters the link sees the entire conversation.

**Comment by elimisteve** [comment]
The room link/invite link includes a passphrase that is quite long and would take an extraordinary amount of computing power to guess, plus an attacker would have to make all those guesses against the server, which would take ever far longer.

I will better document this in the app, thanks.

Regarding message deletion, would it be good enough for you to be able to nuke the entire room as per https://github.com/cryptag/leapchat/issues/204 ?

**Comment by elimisteve** [comment]
@meridia15 Finished! :tada: You can now press the "Delete All Messages Forevec Now" button to delete all messages from that room :slightly_smiling_face:
