### ISSUE TITLE
leapchat.org down

### ISSUE THREAD

**Issue by adana-github** [cryptag/leapchat#214]
Thank you for responding!   Unfortunately it seems it's down again.   I'm with braverangels.org and leapchat is perfect for our workshops, so we love to use it!

Thank you!

**Comment by elimisteve** [comment]
@adana-github I'm glad you enjoy LeapChat! BraverAngels sounds like a great organization; the world could use a _lot_ of political depolarization right now :sweat_smile: .

I've restarted the server and quadruple-checked that it's now working :+1: .
