### ISSUE TITLE
specify the room number 

### ISSUE THREAD

**Issue by SiriusXT** [cryptag/leapchat#224]
I like it very much!

It would be better if itcould specify the room number manually

**Comment by elimisteve** [comment]
Hi @SiriusXT! Thank you, glad you're liking LeapChat.

If you visit a URL like https://www.leapchat.org/#SomethingLongAndRandom , a new room will be created for you at that URL if it doesn't already exist. But be careful with this; that phrase at the end of the URL is used to generate the cryptographic key that is used to encrypt your chat messages! So using a short, non-random passphrase isn't secure.

**Comment by elimisteve** [comment]
@SiriusXT I hope the above answer suffices! Use a long, random room name.
