### ISSUE TITLE
Leapchat certificate failure

### ISSUE THREAD

**Issue by JimiHendricks** [cryptag/leapchat#227]
Leapchat is failing on Apple devices - shows cert revoked. Most Windows devices currently working.

**Comment by adana-github** [comment]
Firefox on windows gives:

An error occurred during a connection to www.leapchat.org. Peer’s Certificate has been revoked.

Error code: SEC_ERROR_REVOKED_CERTIFICATE

**Comment by adana-github** [comment]
Still works on opera and chrome

**Comment by elimisteve** [comment]
Very strange, thanks for the reports! My monitoring service didn't catch it for some reason. May be LetsEncrypt-related... I think LeapChat may still use an old LetsEncrypt endpoint that's going away.

Thanks for the report, @JimiHendricks and @adana-github!

**Comment by elimisteve** [comment]
@JimiHendricks @adana-github LeapChat should now be up for all devices! I checked in Firefox, and the SSL issue that I saw when you helpfully reported the problem is now gone. Thanks!

**Comment by adana-github** [comment]
Thank you!

-Abe
