### ISSUE TITLE
Leapchat is hanging

### ISSUE THREAD

**Issue by adana-github** [cryptag/leapchat#255]
Hello!   When trying to create a chat, I get a url and enter my name, but then it just hangs.

Please help  - Braver Angels (braverangels.org) uses leapchat extensively --we really appreciate it!

**Comment by elimisteve** [comment]
@adana-github Working on it now, thanks!

**Comment by adana-github** [comment]
Hi,  just checking in.  Any news?

Thank you

**Comment by elimisteve** [comment]
@adana-github Whew, finally solved it! Sorry for the downtime, and thank you for using LeapChat :pray: .
