### ISSUE TITLE
site cannot provide secure connection

### ISSUE THREAD

**Issue by adana-github** [cryptag/leapchat#337]
Hello!

Often getting "site cannot provide secure connection"   It happens on edge, firefox , chrome  -- it seems to depend on which device I use.  I can't see a pattern; some windows 11 work and other don't.

**Comment by elimisteve** [comment]
Deploying a new version now that should fix this! Thanks for reporting, @adana-github :+1: .

**Comment by elimisteve** [comment]
Fix deployed. Works for me; let me know if you have any more issues :slightly_smiling_face: .

**Comment by elimisteve** [comment]
Just deployed an even better fix that should fix this issue in all cases, yay :grin: .
