### ISSUE TITLE
Float alert messages above chat messages

### ISSUE THREAD

**Issue by elimisteve** [cryptag/leapchat#60]
Right now the alerts are trapped above the first message in the chat, and therefore won't be seen by the user unless there are like <= 5 messages.

**Comment by jimmcgaw** [comment]
This also removes some bootstrap layout classes from elements that really weren't giving us anything that wasn't just easier to add ourselves. The gutter on either side of the messages list is 15px, which might actually be too much. Might tweak it, 5 would probably be enough.

**Comment by elimisteve** [comment]
@jimmcgaw :+1: Merged
