### ISSUE TITLE
Minify JS in non-dev environments

### ISSUE THREAD

**Issue by jimmcgaw** [cryptag/leapchat#64]

**Comment by jimmcgaw** [comment]
We should minify app.js as part of the build process for non-dev environments. Right now build/app.js is a lot of the code we need for execution, but there's several over js lib files that could be concatenated into a single file and the whole thing could be 'uglify'd.

**Comment by jimmcgaw** [comment]
Part of this should be taking the list of JavaScript files included in index.html file that aren't part of a package management system, moving the list into an external JSON file, and making this part of the build process.

In dev, this JSON file can be parsed and the lines inserted into the index.html file from this JSON file. On building for production environments, this list can be concatted along with all of the JS files and included in app.js build file.

This will also come in handy when writing tests that depend on these external dependencies. mocha or karma, for example, won't be aware of these files in index.html unless we specify them in a config file for the test runner someplace. If this file can live in a single place, all the sweeter.

**Comment by elimisteve** [comment]
99% finished by @jimmcgaw then tweaked by me, and is now done!
