### ISSUE TITLE
Create Header Menu

### ISSUE THREAD

**Issue by jimmcgaw** [cryptag/leapchat#77]
Create a header menu. Start with "mobile first" in mind and develop the mobile web version, keeping in mind that the desktop web version will be differently styled.

Key things:
- Top left: person icon which slide toggles a list of participants (depends on presence, #31)

- Middle: LeapChat logo (need asset for this)

- Top right: Gear icon that expands menu, with single item that allows user to bring up modal to set their username. Or the gear icon could just bring up username modal for now.

Consider desktop design. Sidebar with navigation links grouped by header?

Use styles (background color, text color) from the backchannel project for now.

**Comment by elimisteve** [comment]
@jimmcgaw About to check this out!

In the not-too-distant future we'll want to support multiple rooms. Not sure where this should go, but it may make sense to have the room list on the left like Slack, and a panel on the right that can slide out on mobile or remain visible on desktop/larger screens that shows the room participants.
