### ISSUE TITLE
Implement versioning for static assets

### ISSUE THREAD

**Issue by jimmcgaw** [cryptag/leapchat#81]
Once the app has been released into the wild we'll have browser caching
issues to contend with. We should version assets in production with the
latest and greatest mechanism, which might or might not be the hash
querystring param after the filename. Investigate best solution and add
it.

**Comment by elimisteve** [comment]
@jimmcgaw A quick and good-enough "fix" for v0.3 is just cache-busting by appending a `?` + timestamp (seconds since Unix epoch) to the URLs to the JS and CSS that might change, yes?

**Comment by jimmcgaw** [comment]
That would work. I dig a little digging into tools for this today; they typically append a short hash based on the file contents.

Even the quick and good-enough fix would require some tool to do this for us. Not hard to integrate, I just need to start playing with them.

**Comment by elimisteve** [comment]
@jimmcgaw Do you think React would complain, or that there would be other problems, if we did this for now? http://stackoverflow.com/a/11467981/197160 A JavaScript solution _with no additional tooling required!_
