### ISSUE TITLE
Display User list in sidebar

### ISSUE THREAD

**Issue by jimmcgaw** [cryptag/leapchat#84]
On mobile, the current user list needs to be a list that expands when the users icon at the top left is clicked.

On desktop, the current user list needs to be a list that is diplayed in the sidebar, under the users icon.

**Comment by elimisteve** [comment]
Want to create an empty component for me to populate with the user list?

**Comment by jimmcgaw** [comment]
That was the intent of this: https://github.com/cryptag/leapchat/pull/85/files#diff-e7397b738e0b4d49855b9d97403d8c84

If that can't be merged before tackling this, I can create something else based on master.

**Comment by elimisteve** [comment]
Finished with #31
