### ISSUE TITLE
Clicking Users Icon on mobile toggles user list

### ISSUE THREAD

**Issue by jimmcgaw** [cryptag/leapchat#87]
Right now the users list shows up always on desktop. On mobile web, there's a users icon in the header on the left. When clicked, this needs to animate toggle the users list into view somehow.

**Comment by elimisteve** [comment]
@jimmcgaw I'm working on the logic of this now. Which part do you want to handle, so we don't step on each other's toes?

**Comment by jimmcgaw** [comment]
I'm working on pictures at the moment, then doing some Go with Postgre(SQL|T); that should keep me busy for the next couple of days. Your toes should be good for a while. :)
