### ISSUE TITLE
Alerts should be at the top of the chat section and not cover the left panel

### ISSUE THREAD

**Issue by elimisteve** [cryptag/leapchat#89]
Only an issue on larger screens

**Comment by elimisteve** [comment]
Again, Slack nails it here IMO. @jimmcgaw See the width of the light blue alert-ish bar across the top-ish?

![screenshot-slack-example-forleapchat-screenshot_2017-05-14_20-13-58](https://cloud.githubusercontent.com/assets/139603/26041482/01dfc320-38e2-11e7-9373-680521f1976a.png)

**Comment by jimmcgaw** [comment]
That's actually what I was going for. :) But, flexbox has its quirks so it currently spans the sidebar. I opted to kick the bug down the road.
