### ISSUE TITLE
Use this React pattern and/or Redux

### ISSUE THREAD

**Issue by elimisteve** [cryptag/leapchat#91]
https://twitter.com/dan_abramov/status/824308413559668744/photo/1?ref_src=twsrc%5Etfw&ref_url=https%3A%2F%2Fmedium.freecodecamp.com%2Fmedia%2F1c4129e6d55a4cee7d1883e97f2d207e%3FpostId%3D374f30401b6b

@jimmcgaw

**Comment by elimisteve** [comment]
...and/or use Redux

**Comment by jimmcgaw** [comment]
Most of v0.4 issues depend on proper state management.

**Comment by elimisteve** [comment]
Okay, I'm down to make the switch now. Is there a branch on that? IIRC you
started one, but that was a while ago.

**Comment by Spetastian** [comment]
@elimisteve So we are not currently using the compose method and Redux devtools integration. Also, I added eslint rules and editorconfig to make sure to not mix tabs with spaces and keep it at 2 spaces.

**Comment by elimisteve** [comment]
@Spetastian Thoughts?

**Comment by elimisteve** [comment]
@Spetastian I can close this if it's obvious or irrelevant.

**Comment by Spetastian** [comment]
This can be closed now. From now, if there is some specific case regarding using Redux through the application, we should create specific issues for that if needed.
